---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos7
    image: finnetdevlab/fnn-ansible-managed:centos7
    pre_build_image: True
    privileged: True
    override_command: False
    exposed_ports:
      - 9870/tcp
      - 9000/tcp
    published_ports:
      - 0.0.0.0:9870:9870/tcp
      - 0.0.0.0:9000:900/tcp

provisioner:
  name: ansible
verifier:
  name: ansible
